
name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
          - Android
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Post to the Slack channel
        if: ${{ matrix.targetPlatform == 'Android' }}
        run: |
          pip install -r .github/workflows/slack/requirements.txt
          python .github/workflows/slack/__init__.py Android ProjectSettings/boot.config
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
